### ISSUE TITLE
Provide simple usage example

### ISSUE THREAD

**Issue by fabian-schlegel** [imagov/keycloak#1]
For a better understanding how to use this gem to interact with KeyCloak, a short and simple usage example would be great!

**Comment by g-portugues** [comment]
hello, fabian-schlegel

I'm working on it. I'll make the examples available soon.

Thank you

**Comment by krunalpuri** [comment]
Hello,  
Kindly let us know if you have a sample usage implementation or tutorials for this gem.
Appreciate your help.
Thank you !!

**Comment by swissmadekzu** [comment]
I must admit that some samples would really be helpful, I'm really having trouble to implement it.

**Comment by pplant** [comment]
+1

**Comment by g-portugues** [comment]
Hi,

I finally got the time to make a simple example of using gem. I hope it helps!
Soon I'll be posting an example of how to use gem for APIs projects.

https://github.com/imagov/example-gem-keycloak

Thanks

**Comment by davidkirwan** [comment]
Nice one @g-portugues !
