### ISSUE TITLE
Is this project still maintained by anyone?

### ISSUE THREAD

**Issue by rahulbajaj0509** [imagov/keycloak#10]
I was thinking of contributing to the GEM so that I don't have to re-event the wheel, but it seems like the project does not have any maintainer!

**Comment by lvitals** [comment]
Welcome @rahulbajaj0509, feel free to contribute, the project has maintainers and is being developed by a team based in a public company in Brazil

**Comment by rahulbajaj0509** [comment]
Thank you so much for your response :)
