### ISSUE TITLE
Set verify_ssl = false

### ISSUE THREAD

**Issue by whitewolf92** [imagov/keycloak#25]
Is there anywhere I can set **verify_ssl=false** on the RestClient function that is being used by keycloak?

I needed RestClient to connect to https that has invalid cert. 

is there any ways to do it? Thanks .

**Comment by g-portugues** [comment]
Hello, @whitewolf92 !
Unfortunately there is no way.
I would appreciate it if you opened a Pull Request with this feature.
Thank you!

**Comment by whitewolf92** [comment]
Hey G,

thanks for the reply. much appreciated.

I use your raw code to test with **verify_ssl=false** first and if it works, I will open a pull request. 

Just a quick qns, why did u consider rest-client over httparty?

**Comment by yubi-manoj-deshpande** [comment]
@whitewolf92 
Have you created a pull request? Let me know if it is done. In dire need of it.
