### ISSUE TITLE
Keycloak.proc_cookie_token is not thread safe

### ISSUE THREAD

**Issue by pplant** [imagov/keycloak#26]
Hi,

recently I found an issue with using the keycloak gem inside a Rails application backed by the Puma web server with a multi-threaded setup. When simulating multiple requests coming from two different sessions the content of the keycloak_token cookie gets overwritten. This results into processing a request with a "foreign" access_token potentially exposing sensitiv data. After excluding all kinds of sources for the error. I came to the conclusion that the following line of code inside the ApplicationController initialize function

`Keycloak.proc_cookie_token = -> do
  cookies.permanent[:keycloak_token]
end`

as described in your README (...Note: The Keycloak.proc_cookie_token and Keycloak.proc_external_attributes attributes can be defined in the initialize of the controller ApplicationController...) is the source of the problem. If multiple requests from different sessions are rolling in it comes to a race condition wrongly altering the access_token for some of the requests.

If you need further information please let me know. I also wrote a small ruby script showcasing the issue in a nutshell (not related to keycloak but using a lambda set to a static variable using multiple threads)

Gem version: 2.4.1
Rails version: 5.2.3
Ruby version: 2.6.3

**Comment by Defoncesko** [comment]
Hey @pplant

We are facing the same issue here as you described.

Could you please share your script ?

**Comment by pplant** [comment]
@Defoncesko check the PR i created there you have all the changes you need to fix this issue
