### ISSUE TITLE
Do not pin versions of dependent gems exactly

### ISSUE THREAD

**Issue by Timmitry** [imagov/keycloak#29]
Hey there 👋 

I just noticed after bundle updating our project that the newest version of keycloak has these dependencies:

```
    keycloak (3.2.1)
      json (= 2.3.0)
      jwt (= 2.2.1)
      rest-client (= 2.1.0)
```

I think this is problematic - imagine another gem which depends on `json`, but specifies `= 2.3.1`. This would not allow installing both gems at the same time. I think it would be better to e.g. only specify something like `~> 2.3`, which would allow patch and minor updates. What do you think? 🙂

**Comment by simlegate** [comment]
I got same issues.
My project is still using the json version `~ 1.8` and it is hard to upgrade this json because it will be a break change.
