### ISSUE TITLE
README file in english

### ISSUE THREAD

**Issue by swissmadekzu** [imagov/keycloak#3]
Hi,

I'd like to know if you plan on translating the README into english, as I (sadly) can't read Portuguese.

Thanks in advance,

**Comment by jaybloke** [comment]
This gem is exactly what I need... but I too can't read Portuguese!

**Comment by g-portugues** [comment]
Hi,

I'm almost finishing the translation. I have published what I have already translated.
I hope to finish the translation later this week.

Thank you!

**Comment by g-portugues** [comment]
Now all documentation is available in English.
