### ISSUE TITLE
Keycloak version 11 breaks `token_introspection_endpoint`

### ISSUE THREAD

**Issue by kgbsmurf** [imagov/keycloak#31]
According to https://www.keycloak.org/docs/latest/upgrading/#non-standard-token-introspection-endpoint-removed the Keycloak version 11 change the name of the `introspection_endpoint` key.  This means that there should be version-sensitive or some other logic to properly get introspection endpoint url.   

Potentially this code:
```
token_introspection_endpoint = @configuration['token_introspection_endpoint'] if isempty?(token_introspection_endpoint)
```
could be updated as follows:

```
token_introspection_endpoint = (@configuration['introspection_endpoint'] || @configuration['token_introspection_endpoint']) if isempty?(token_introspection_endpoint)
```

What do you think about this update?

**Comment by kjoscha** [comment]
Thank you @kgbsmurf , that fixes the login for me :)

**Comment by vinaykp3** [comment]
Yes, faced same issue and these changes works for me too. can maintainers merge this PR.?
