### ISSUE TITLE
Keycloak openid_configuration fails with error when Keycloak.proxy is nil

### ISSUE THREAD

**Issue by tmertens** [imagov/keycloak#5]
When using Keycloak without a proxy, if the proxy is not explicitly set to an empty string `''`, then certain Keycloak requests will fail with `NoMethodError: undefined method `empty?' for nil:NilClass`.

This is caused by calling `empty?` on `Keycloak.proxy` here: https://github.com/imagov/keycloak/blob/master/lib/keycloak.rb#L331 .  In a non-rails project without ActiveSupport, the `empty?` method is not present on `NilClass`.

**Solution:**
Check for nil before attempting to call `empty?`, or use the safe navigator operator.
A major caveat to using the safe navigator operator in a gem is that it is only present in ruby versions 2.3.0 and newer.

**Comment by g-portugues** [comment]
Thanks for your tip.
In version 2.4.0 I happened to check with the `present?` method, so I think it will solve the problem.
