### ISSUE TITLE
Keycloak raises ActionController::RoutingError, which does not exist in the gem

### ISSUE THREAD

**Issue by tmertens** [imagov/keycloak#6]
Keycloak implicitly depends on Ruby on Rails because it depends on Rails constants being present and loaded when performing certain actions.

For example, here it raises `ActionController::RoutingError`, which is a rails-specific error and which neither exists in the keycloak gem nor in the gem's dependencies specified in the gemfile.  https://github.com/imagov/keycloak/blob/master/lib/keycloak.rb#L876

The gem should not implicitly depend on any libraries not explicitly included in the gemfile.

**Comment by g-portugues** [comment]
i've fixed it in 3.0.0
